import './globals.css'
import { Open_Sans } from 'next/font/google';
import Navbar from './(shared)/Navbar';

export const metadata = {
  title: 'Blog AI app',
  description: 'Generated by create next app',
}

const openSans = Open_Sans({
  subsets:['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        {/* <Footer/> */}
        </body>
    </html>
  )
}
